#! /bin/bash
# Generate latex tables of run-times for MrE, for inputs
# of varying sizes (ss), using each of the available
# simplification options.  A table is generated for each
# of several alphabet widths (ws).

ss="10 20 40 80 160 320 640 1280 2560"
ws="1 2 3 4 8 16"

allsizes() {
echo $3
for s in $ss
do echo -n ' & '
   (time -p ./MrE $2 -S${s} -W$1) > /dev/null 2> time.out
   grep real time.out | sed "s/[^0-9]*\(.*\)/\1/"
done
echo ' \\'
}

for w in $ws
do
echo '\begin{figure}\begin{tabular}{rrrrrrrrrr}'
echo ' & \multicolumn{9}{c}{Simplifying 1000 expressions of size:} \\'
for s in $ss ; do echo -n " & $s" ; done
echo ' \\'
allsizes $w -g "Gruber-Gulan+"
allsizes $w -n "normalise"
allsizes $w -f "+ fuse"
allsizes $w -l "+ promote"
allsizes $w -s "+ stellate"
allsizes $w -p "+ press"
allsizes $w -y "+ syn. search"
allsizes $w -c "+ sem. search"
# allsizes $w -m museum
echo '\end{tabular}\caption{Run-times (s) for alphabets of size' $w.'}\end{figure}'
done
